networks:
  kafka-network:
    name: kafka-network
    driver: bridge
    
services:
    zookeeper1:
            image: confluentinc/cp-zookeeper:latest
            container_name: zookeeper1
            environment:
              - ZOOKEEPER_CLIENT_PORT=2181
              - ZOOKEEPER_TICK_TIME=2000
            ports:
              - 22181:2181
            networks:
              - kafka-network
    zookeeper2:
            image: confluentinc/cp-zookeeper:latest
            container_name: zookeeper2
            environment:
              - ZOOKEEPER_CLIENT_PORT=2181
              - ZOOKEEPER_TICK_TIME=2000
            ports:
              - 23181:2181
            networks:
              - kafka-network
    kafka1:
            image: confluentinc/cp-kafka:latest
            container_name: kafka1
            depends_on:
              - zookeeper1
              - zookeeper2
            ports:
              - 24092:24092
              - 24192:24192
            networks:
              - kafka-network
            environment:
              - KAFKA_BROKER_ID=1
              - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181
              - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:24092,PLAINTEXT_HOST://localhost:24192
              - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
              - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
              - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    kafka2:
            image: confluentinc/cp-kafka:latest
            container_name: kafka2
            depends_on:
              - zookeeper1
              - zookeeper2
            ports:
              - 25092:25092
              - 25192:25192
            networks:
              - kafka-network
            environment:
              - KAFKA_BROKER_ID=2
              - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181
              - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:25092,PLAINTEXT_HOST://localhost:25192
              - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
              - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
              - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    kafka3:
            image: confluentinc/cp-kafka:latest
            container_name: kafka3
            depends_on:
              - zookeeper1
              - zookeeper2
            ports:
              - 26092:26092
              - 26192:26192
            networks:
              - kafka-network
            environment:
              - KAFKA_BROKER_ID=3
              - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181
              - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:26092,PLAINTEXT_HOST://localhost:26192
              - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
              - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
              - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    kafka-ui:
            image: provectuslabs/kafka-ui:latest
            container_name: kafka-ui
            depends_on:
              - zookeeper1
              - zookeeper2
              - kafka1
              - kafka2
              - kafka3
            environment:
              - KAFKA_CLUSTERS_0_NAME=meucluster
              - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:24092,kafka2:25092,kafka3:26092
              - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper1:22181,zookeeper2:23181
            ports:
              - 27080:8080
            networks:
              - kafka-network